In [2]:
import pandas as pd
import numpy as np
df= pd.read_csv("DSA.csv")
df.head(2)

Links  Que_Language  \
0    https://leetcode.com/problems/maximum-subarray/      English   
1  https://leetcode.com/problems/best-time-to-buy...      English   

   vote_average  vote_count   Type  \
0           7.2       11800  array   
1           6.9        4500  array   

                                            problems  \
0  Given an integer array nums, find the \nsubarr...   
1  You are given an array prices where prices[i] ...   

                         Topic  
0             Maximum Subarray  
1  Best Time to Buy Sell Stock

In [3]:
df.head(1)['problems']

0    Given an integer array nums, find the \nsubarr...
Name: problems, dtype: object

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfv = TfidfVectorizer(min_df=3, max_features=None,
                     strip_accents='unicode', analyzer='word', token_pattern=r'\w{1,}',
                     ngram_range=(1,2),
                     stop_words ='english')

In [5]:
df['problems'] = df['problems'].fillna('')

#Fitting  the TF_IDF on the 'problem' text

tfv_matrix = tfv.fit_transform(df['problems'])

In [6]:
tfv_matrix

<83x179 sparse matrix of type '<class 'numpy.float64'>'
	with 1221 stored elements in Compressed Sparse Row format>

In [22]:
tfv_matrix.shape
print (tfv_matrix)
print("TF-IDF Matrix:", tfv_matrix.toarray())

  (0, 16)	0.2786369790128709
  (0, 67)	0.270643172705671
  (0, 49)	0.270643172705671
  (0, 134)	0.13246235317559987
  (0, 162)	0.5747864062323935
  (0, 77)	0.37157358141956986
  (0, 160)	0.37157358141956986
  (0, 110)	0.25014279230002456
  (0, 14)	0.18957735765810318
  (0, 66)	0.20696317480794427
  (0, 46)	0.10228241609892472
  (1, 72)	0.25565104086052254
  (1, 157)	0.25565104086052254
  (1, 53)	0.25565104086052254
  (1, 125)	0.24345369085907229
  (1, 127)	0.25565104086052254
  (1, 128)	0.25565104086052254
  (1, 17)	0.25565104086052254
  (1, 47)	0.18215365066478706
  (1, 30)	0.24345369085907229
  (1, 71)	0.24345369085907229
  (1, 156)	0.24345369085907229
  (1, 124)	0.24345369085907229
  (1, 126)	0.48690738171814457
  (1, 14)	0.13804998122587972
  :	:
  (81, 18)	0.6178603346393137
  (81, 45)	0.44755825392059784
  (81, 102)	0.2874452755557013
  (81, 173)	0.3461634696523082
  (81, 176)	0.44755825392059784
  (81, 46)	0.12319858527381251
  (82, 103)	0.21084733818418477
  (82, 166)	0.2108473

In [26]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfv_matrix)
print(cosine_sim)


[[1.         0.04140753 0.12226158 ... 0.15735125 0.01260105 0.01766376]
 [0.04140753 1.         0.76640207 ... 0.00457901 0.01835213 0.00960912]
 [0.12226158 0.76640207 1.         ... 0.0332264  0.01168297 0.011247  ]
 ...
 [0.15735125 0.00457901 0.0332264  ... 1.         0.14026823 0.21374148]
 [0.01260105 0.01835213 0.01168297 ... 0.14026823 1.         0.15115105]
 [0.01766376 0.00960912 0.011247   ... 0.21374148 0.15115105 1.        ]]


In [29]:
from sklearn.metrics import jaccard_score
jaccard_sim = jaccard_

In [8]:
from sklearn.metrics.pairwise import sigmoid_kernel

sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [9]:
sig[0]

array([0.76393042, 0.76169129, 0.76188086, 0.76167808, 0.7619731 ,
       0.76189184, 0.76182575, 0.76159416, 0.76192402, 0.7621033 ,
       0.76162185, 0.76232014, 0.76184372, 0.76286434, 0.76170008,
       0.76176955, 0.76159416, 0.76165578, 0.76163257, 0.76247176,
       0.76217505, 0.76207472, 0.7618235 , 0.7616694 , 0.76205301,
       0.76189914, 0.76182032, 0.7616852 , 0.7623866 , 0.76164435,
       0.76163112, 0.76179245, 0.76167313, 0.76163263, 0.76178763,
       0.76159416, 0.7617345 , 0.76159416, 0.76165275, 0.76167425,
       0.76163515, 0.76167055, 0.76165428, 0.76161717, 0.76188711,
       0.76164719, 0.7616387 , 0.76164521, 0.76166742, 0.76165307,
       0.76160415, 0.76162087, 0.76162148, 0.76164361, 0.761729  ,
       0.76160904, 0.76159416, 0.76172257, 0.76214622, 0.76217007,
       0.76230518, 0.76159781, 0.76185216, 0.76170384, 0.76162644,
       0.76159416, 0.76159416, 0.76160823, 0.76165345, 0.76184424,
       0.76232528, 0.76215756, 0.76207881, 0.76165718, 0.76165

In [10]:
indices = pd.Series(df.index, index= df['Topic']).drop_duplicates()

In [11]:
indices


Topic
 Maximum Subarray                            0
Best Time to Buy Sell Stock                  1
 Best Time to Buy Sell Stock II              2
Best Time to Buy Sell Stock III              3
Best Time to Buy Sell Stock IV               4
                                            ..
Balanced Binary Tree                        78
Diameter of Binary Tree                     79
Binary Tree Maximum Path Sum                80
Same Tree                                   81
Binary Tree Zigzag Level Order Traversal    82
Length: 83, dtype: int64

In [12]:
def give_rec(Topic, sig=sig):
    
    idx = indices[Topic]
    
    sig = list(enumerate(sig[idx]))
    
    sig = sorted(sig, reverse= True, key=lambda x: x[1])
    
    sig = sig[1:10]
    
    q_indices = [i[0] for i in sig]
    
    return df['Topic'].iloc[q_indices]

In [13]:
give_rec("Best Time to Buy Sell Stock")

3                      Best Time to Buy Sell Stock III
2                       Best Time to Buy Sell Stock II
4                       Best Time to Buy Sell Stock IV
61                  Minimum Cost Tree From Leaf Values
71                              Grumpy Bookstore Owner
59                            Sum of Subarray Minimums
13    Count the number of subarrays having a given XOR
31                                          Flood Fill
14                                    Fibonacci Number
Name: Topic, dtype: object

In [14]:
sig[0]

array([0.76393042, 0.76169129, 0.76188086, 0.76167808, 0.7619731 ,
       0.76189184, 0.76182575, 0.76159416, 0.76192402, 0.7621033 ,
       0.76162185, 0.76232014, 0.76184372, 0.76286434, 0.76170008,
       0.76176955, 0.76159416, 0.76165578, 0.76163257, 0.76247176,
       0.76217505, 0.76207472, 0.7618235 , 0.7616694 , 0.76205301,
       0.76189914, 0.76182032, 0.7616852 , 0.7623866 , 0.76164435,
       0.76163112, 0.76179245, 0.76167313, 0.76163263, 0.76178763,
       0.76159416, 0.7617345 , 0.76159416, 0.76165275, 0.76167425,
       0.76163515, 0.76167055, 0.76165428, 0.76161717, 0.76188711,
       0.76164719, 0.7616387 , 0.76164521, 0.76166742, 0.76165307,
       0.76160415, 0.76162087, 0.76162148, 0.76164361, 0.761729  ,
       0.76160904, 0.76159416, 0.76172257, 0.76214622, 0.76217007,
       0.76230518, 0.76159781, 0.76185216, 0.76170384, 0.76162644,
       0.76159416, 0.76159416, 0.76160823, 0.76165345, 0.76184424,
       0.76232528, 0.76215756, 0.76207881, 0.76165718, 0.76165

In [15]:
list(enumerate(sig[indices['Balanced Binary Tree']]))

[(0, 0.7616360063091577),
 (1, 0.7616551045884763),
 (2, 0.7616329574172147),
 (3, 0.7616468152120764),
 (4, 0.7616409614358475),
 (5, 0.7616291531767587),
 (6, 0.7616238965425153),
 (7, 0.7615941559557649),
 (8, 0.7616186779634092),
 (9, 0.7616327180224041),
 (10, 0.7616117971807751),
 (11, 0.7616151676382641),
 (12, 0.7616293575777743),
 (13, 0.7616407167635856),
 (14, 0.7616348834545875),
 (15, 0.7616119739716943),
 (16, 0.7615941559557649),
 (17, 0.7616334041631001),
 (18, 0.7616596574807121),
 (19, 0.761634002738637),
 (20, 0.7616193917704271),
 (21, 0.761632854155246),
 (22, 0.7616393372905035),
 (23, 0.7616236225218553),
 (24, 0.7616293756935686),
 (25, 0.7616251447358754),
 (26, 0.7615941559557649),
 (27, 0.7616521480165667),
 (28, 0.76162413026191),
 (29, 0.7616261251906739),
 (30, 0.7616176986032681),
 (31, 0.7616202068032346),
 (32, 0.7616140450385378),
 (33, 0.7616186603036567),
 (34, 0.761615515324734),
 (35, 0.7615941559557649),
 (36, 0.7621010622169374),
 (37, 0.76159415

In [16]:
sorted(list(enumerate(sig[indices['Balanced Binary Tree']])), key=lambda x: x[1], reverse=True)




[(78, 0.763930416896351),
 (79, 0.7629139959251181),
 (77, 0.7627007265316574),
 (73, 0.7625190965516172),
 (74, 0.7625190965516172),
 (75, 0.7625190965516172),
 (81, 0.7622777000290318),
 (82, 0.7622026417617802),
 (76, 0.7621862622248969),
 (80, 0.7621615542849938),
 (36, 0.7621010622169374),
 (68, 0.7618692706056053),
 (55, 0.7618680042889322),
 (72, 0.7618169595679005),
 (46, 0.7617824766135762),
 (65, 0.7617527956046609),
 (57, 0.7617326042067004),
 (52, 0.7617209851680297),
 (18, 0.7616596574807121),
 (1, 0.7616551045884763),
 (27, 0.7616521480165667),
 (3, 0.7616468152120764),
 (59, 0.7616450599789379),
 (4, 0.7616409614358475),
 (13, 0.7616407167635856),
 (51, 0.7616397012197941),
 (22, 0.7616393372905035),
 (71, 0.7616368313899503),
 (0, 0.7616360063091577),
 (14, 0.7616348834545875),
 (19, 0.761634002738637),
 (17, 0.7616334041631001),
 (43, 0.761633401851664),
 (2, 0.7616329574172147),
 (21, 0.761632854155246),
 (9, 0.7616327180224041),
 (42, 0.7616324529709949),
 (49, 0.761

In [17]:
give_rec("Sliding Window Maximum")

70                                Sliding Window Median
51    Convert Binary Number in a Linked List to Integer
5                             Find the Duplicate Number
12                         Longest Consecutive Sequence
23                                      Combination Sum
72                             Max Consecutive Ones III
59                             Sum of Subarray Minimums
28                              Palindrome Partitioning
82             Binary Tree Zigzag Level Order Traversal
Name: Topic, dtype: object

In [18]:
give_rec("Sum of Subarray Minimums")

5                            Find the Duplicate Number
13    Count the number of subarrays having a given XOR
67                              Rotting Oranges (VVVI)
14                                    Fibonacci Number
60                                   Online Stock Span
69                              Sliding Window Maximum
31                                          Flood Fill
72                            Max Consecutive Ones III
0                                     Maximum Subarray
Name: Topic, dtype: object

In [19]:
give_rec("Convert Binary Number in a Linked List to Integer")

54                     Valid Parentheses
52    Remove Duplicates from Sorted List
42          Delete Node in a Linked List
48                Palindrome Linked List
46                  Linked List Cycle II
38             Middle of the Linked List
47              Reverse Nodes in k-Group
53           Remove Linked List Elements
39                Merge Two Sorted Lists
Name: Topic, dtype: object

In [20]:
give_rec("Balanced Binary Tree")

79                     Diameter of Binary Tree
77                Maximum Depth of Binary Tree
73              Binary Tree Preorder Traversal
74               Binary Tree Inorder Traversal
75             Binary Tree Postorder Traversal
81                                   Same Tree
82    Binary Tree Zigzag Level Order Traversal
76           Binary Tree Level Order Traversal
80                Binary Tree Maximum Path Sum
Name: Topic, dtype: object